subinclude("//build_defs/npm")

filegroup(
  name = "puppeteer_deps",
  srcs = ["_withPage.ts"],
)

# ava_test(
#   name = "puppeteer",
#   srcs = glob(["**/*.spec.ts"]),
#   deps = [
#     "//:ava_test_deps",
#     ":puppeteer_deps",
#   ]
# )
