// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/enum/access_level.wings)
// and run the following command:
// plz build //src/wings/...

enum AccessLevel {
  None,
  View,
  Edit,
  Owner,
}

export default AccessLevel;
