// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/auth.wings)
// and run the following command:
// plz build //src/wings/...


// 
export default class Auth {
  [key: string]: any;
  public ID: Number = -1;
  public username: String = '';
  public confirmed: Boolean = false;

  public constructor(obj?: any) {
    if (obj) {
      this.ID = obj.id !== undefined && obj.id !== null ? obj.id : -1;
      this.username = obj.username !== undefined && obj.username !== null ? obj.username : '';
      this.confirmed = obj.confirmed !== undefined && obj.confirmed !== null ? obj.confirmed : false;
    }
  }

  public toJsonKey(key: string): string {
    switch (key) {
      case 'ID': {
        return 'id';
      }
      case 'username': {
        return 'username';
      }
      case 'confirmed': {
        return 'confirmed';
      }
      default: {
        return key;
      }
    }
  }
}
