filegroup(
  name = "wings",
  srcs = [
    "//src/wings/enum:_city#ts",
    "//src/wings/enum:_access_level#ts",
    "//src/wings/struct:_day#ts",
    "//src/wings/struct:_new_user#ts",
    "//src/wings/struct:_place#ts",
    "//src/wings/struct:_trip#ts",
    "//src/wings/struct:_user#ts",
    "//src/wings/struct:_user_access_level#ts",
    "//src/wings/struct:_confirm_email#ts",
  ],
  visibility = [
    "//:cockpit",
    "//:ava_test_deps",
    "//src/cockpit/...",
  ],
)
