filegroup(
  name = "wings",
  srcs = [
    "//src/wings/enum:city_#ts",
    "//src/wings/enum:access_level_#ts",
    "//src/wings/struct:day_#ts",
    "//src/wings/struct:new_user_#ts",
    "//src/wings/struct:place_#ts",
    "//src/wings/struct:trip_#ts",
    "//src/wings/struct:user_#ts",
    "//src/wings/struct:user_access_level_#ts",
    "//src/wings/struct:confirm_email_#ts",
  ],
  visibility = ["//src/cockpit/..."],
)
