// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/enum/city.wings)
// and run the following command:
// plz build //src/wings/...

enum City {
  UNKNOWN,
  SanFranciscoCAUS,
  SanJoseCAUS,
  NewYorkNYUS,
  AnchorageAKUS,
  ParisFR,
  KualaLumpurMY,
  GeorgeTownPGMY,
  SeattleWAUS,
  WashingtonDCUS,
  BostonMAUS,
  PhoneixAZUS,
  PageAZUS,
  LosAngelesCAUS,
  LasVegasNVUS,
  SantaCruzCAUS,
}

export default City;
