// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/login_credential.wings)
// and run the following command:
// plz build //src/wings/...

import { IWingsStruct } from 'wings-ts-util';

// Login credential
export default class LoginCredential implements IWingsStruct {
  [key: string]: any;
  public email: String = '';
  public password: String = '';

  public constructor(obj?: any) {
    if (obj) {
      this.email = obj.email !== undefined && obj.email !== null ? obj.email : '';
      this.password = obj.password !== undefined && obj.password !== null ? obj.password : '';
    }
  }

  public toJsonKey(key: string): string {
    switch (key) {
      case 'email': {
        return 'email';
      }
      case 'password': {
        return 'password';
      }
      default: {
        return key;
      }
    }
  }
}
