// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/parsed_city.wings)
// and run the following command:
// plz build //src/wings/...

import { IWingsStruct } from 'wings-ts-util';

// City object queried from DB
export default class ParsedCity implements IWingsStruct {
  [key: string]: any;
  public ID: Number = 0;
  public display: String = '';
  public iso2: String = '';

  public constructor(obj?: any) {
    if (obj) {
      this.ID = obj.id !== undefined && obj.id !== null ? obj.id : 0;
      this.display = obj.display !== undefined && obj.display !== null ? obj.display : '';
      this.iso2 = obj.iso2 !== undefined && obj.iso2 !== null ? obj.iso2 : '';
    }
  }

  public toJsonKey(key: string): string {
    switch (key) {
      case 'ID': {
        return 'id';
      }
      case 'display': {
        return 'display';
      }
      case 'iso2': {
        return 'iso2';
      }
      default: {
        return key;
      }
    }
  }
}
