// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/registration_response.wings)
// and run the following command:
// plz build //src/wings/...

import { IWingsStruct } from 'wings-ts-util';
import RegistrationError from './RegistrationError';
import UserObj from './UserObj';

// Response for registration attempt
export default class RegistrationResponse implements IWingsStruct {
  [key: string]: any;
  public error: RegistrationError = RegistrationError.InvalidType;
  public user: UserObj = new UserObj();

  public constructor(obj?: any) {
    if (obj) {
      this.error = obj.error !== undefined && obj.error !== null ? obj.error : RegistrationError.InvalidType;
      this.user = obj.user !== undefined && obj.user !== null ? new UserObj(obj.user) : new UserObj();
    }
  }

  public toJsonKey(key: string): string {
    switch (key) {
      case 'error': {
        return 'error';
      }
      case 'user': {
        return 'user';
      }
      default: {
        return key;
      }
    }
  }
}
