// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/travel_time.wings)
// and run the following command:
// plz build //src/wings/...

import { IWingsStruct } from 'wings-ts-util';

// Time take to travel from one place to another.
export default class TravelTime implements IWingsStruct {
  [key: string]: any;
  public ID: Number = -1;
  public fromPlaceID: Number = 0;
  public toPlaceID: Number = 0;
  public toPlaceIndex: Number = 0;
  public timeInMinutes: Number = 0;

  public constructor(obj?: any) {
    if (obj) {
      this.ID = obj.id !== undefined && obj.id !== null ? obj.id : -1;
      this.fromPlaceID = obj.from_place_id !== undefined && obj.from_place_id !== null ? obj.from_place_id : 0;
      this.toPlaceID = obj.to_place_id !== undefined && obj.to_place_id !== null ? obj.to_place_id : 0;
      this.toPlaceIndex = obj.to_place_index !== undefined && obj.to_place_index !== null ? obj.to_place_index : 0;
      this.timeInMinutes = obj.time_in_minutes !== undefined && obj.time_in_minutes !== null ? obj.time_in_minutes : 0;
    }
  }

  public toJsonKey(key: string): string {
    switch (key) {
      case 'ID': {
        return 'id';
      }
      case 'fromPlaceID': {
        return 'from_place_id';
      }
      case 'toPlaceID': {
        return 'to_place_id';
      }
      case 'toPlaceIndex': {
        return 'to_place_index';
      }
      case 'timeInMinutes': {
        return 'time_in_minutes';
      }
      default: {
        return key;
      }
    }
  }
}
