// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/trip_search_query.wings)
// and run the following command:
// plz build //src/wings/...

import { IWingsStruct } from 'wings-ts-util';
import City from './City';
import { parseArray } from 'wings-ts-util';

// Search query for trips
export default class TripsSearchQuery implements IWingsStruct {
  [key: string]: any;
  public cities: City[] = [];
  public length: Number = 0;
  public query: String = '';

  public constructor(obj?: any) {
    if (obj) {
      this.cities = obj.cities !== undefined && obj.cities !== null ? parseArray<City>(City, obj.cities) : [];
      this.length = obj.length !== undefined && obj.length !== null ? obj.length : 0;
      this.query = obj.query !== undefined && obj.query !== null ? obj.query : '';
    }
  }

  public toJsonKey(key: string): string {
    switch (key) {
      case 'cities': {
        return 'cities';
      }
      case 'length': {
        return 'length';
      }
      case 'query': {
        return 'query';
      }
      default: {
        return key;
      }
    }
  }
}
