pull_request_rules:
  - name: renovate-bot updates
    conditions:
      - "author=renovate[bot]"
      - "status-success=CodeFactor"
      - "status-success=build"
      - "status-success=e2e"
      - "status-success=turbine"
      - "status-success=cockpit"
      - "status-success=no_go_mod"
      - "status-success=binhonglee.GlobeTrotte"
      - "status-success=codebeat"
      - "status-success=license/cla"
    actions:
      merge:
        method: squash
  - name: Approved PRs (binhonglee)
    conditions:
      - "approved-reviews-by=binhonglee"
      - "status-success=CodeFactor"
      - "status-success=build"
      - "status-success=e2e"
      - "status-success=turbine"
      - "status-success=cockpit"
      - "status-success=coverage"
      - "status-success=binhonglee.GlobeTrotte"
      # - "status-success=ci/circleci: build"
      - "status-success=codebeat"
      - "status-success=license/cla"
    actions:
      merge:
        method: squash
  - name: Approved PRs (samueljklee)
    conditions:
      - "approved-reviews-by=samueljklee"
      - "status-success=CodeFactor"
      - "status-success=build"
      - "status-success=e2e"
      - "status-success=turbine"
      - "status-success=cockpit"
      - "status-success=coverage"
      - "status-success=binhonglee.GlobeTrotte"
      # - "status-success=ci/circleci: build"
      - "status-success=codebeat"
      - "status-success=license/cla"
    actions:
      merge:
        method: squash
