variables:
  HOMEBREW_NO_INSTALL_CLEANUP: 1
  HOMEBREW_NO_AUTO_UPDATE: 1

trigger:
  branches:
    exclude:
    - prod

jobs:
- job: Build
  pool:
    vmImage: $(imageName)
  strategy:
    matrix:
      ubuntu-node-16-go-1-16-6:
        imageName: "ubuntu-latest"
        nodeVersion: "16.x"
        goVersion: "1.16.6"
      mac-node-16-go-1-16-6:
        imageName: "macos-latest"
        nodeVersion: "16.x"
        goVersion: "1.16.6"

  steps:
  - task: GoTool@0
    inputs:
      version: $(goVersion)
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)

  - task: Cache@2
    inputs:
      key: "pnpm_store | $(Agent.OS) | package.json"
      path: "/home/vsts/.pnpm-store"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Cache pnpm-store (Ubuntu)

  - task: Cache@2
    inputs:
      key: "pnpm_store | $(Agent.OS) | package.json"
      path: "/Users/runner/.pnpm-store"
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Cache pnpm-store (MacOS)

  - task: Cache@2
    inputs:
      key: "cypress | $(Agent.OS) | package.json"
      path: "/home/vsts/.cache/Cypress"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Cache Cypress (Ubuntu)

  - task: Cache@2
    inputs:
      key: "cypress | $(Agent.OS) | package.json"
      path: "/Users/runner/Library/Caches/Cypress"
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Cache Cypress (MacOS)

  - script: ./scripts/setup.sh
    displayName: Run install script

  - script: |
      DIR=$(basename $CURRENT_DIR)
      sed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Fix wings.json (Ubuntu)

  - script: |
      brew install gnu-sed
      DIR=$(basename $CURRENT_DIR)
      gsed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Fix wings.json (MacOS)

  - script: ./pleasew build --show_all_output //...
    displayName: Build all

  - script: ./pleasew lint
    displayName: Lint changes

  - script: |
      git checkout wings.json
      ./scripts/leftover.sh
    displayName: Check for leftover

- job: E2E
  pool:
    vmImage: $(imageName)
  strategy:
    matrix:
      ubuntu-node-16-go-1-16-6:
        imageName: "ubuntu-latest"
        nodeVersion: "16.x"
        goVersion: "1.16.6"
      # mac-node-16-go-1-16-6:
      #   imageName: "macos-latest"
      #   nodeVersion: "16.x"
      #   goVersion: "1.16.6"

  steps:
  - task: GoTool@0
    inputs:
      version: $(goVersion)
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)

  - task: Cache@2
    inputs:
      key: "pnpm_store | $(Agent.OS) | package.json"
      path: "/home/vsts/.pnpm-store"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Cache pnpm-store (Ubuntu)

  - task: Cache@2
    inputs:
      key: "pnpm_store | $(Agent.OS) | package.json"
      path: "/Users/runner/.pnpm-store"
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Cache pnpm-store (MacOS)

  - task: Cache@2
    inputs:
      key: "cypress | $(Agent.OS) | package.json"
      path: "/home/vsts/.cache/Cypress"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Cache Cypress (Ubuntu)

  - task: Cache@2
    inputs:
      key: "cypress | $(Agent.OS) | package.json"
      path: "/Users/runner/Library/Caches/Cypress"
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Cache Cypress (MacOS)

  - script: ./scripts/setup.sh
    displayName: Run install script

  - script: |
      DIR=$(basename $CURRENT_DIR)
      sed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Fix wings.json (Ubuntu)

  - script: |
      brew install gnu-sed
      DIR=$(basename $CURRENT_DIR)
      gsed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Fix wings.json (MacOS)

  - script: ./pleasew build "//src/turbine:main"
    displayName: Build turbine

  - script: ./pleasew run "//src/turbine:main" &
    displayName: Run turbine on background
  - script: sleep 1
  - script: ./pleasew test --show_all_output //:cockpit_cypress
    displayName: Run e2e tests

- job: turbine
  pool:
    vmImage: $(imageName)
  strategy:
    matrix:
      ubuntu-node-16-go-1-16-6:
        imageName: "ubuntu-latest"
        nodeVersion: "16.x"
        goVersion: "1.16.6"
      mac-node-16-go-1-16-6:
        imageName: "macos-latest"
        nodeVersion: "16.x"
        goVersion: "1.16.6"

  steps:
  - task: GoTool@0
    inputs:
      version: $(goVersion)

  - script: ./scripts/setup.sh -gqc
    displayName: Run install script

  - script: |
      DIR=$(basename $CURRENT_DIR)
      sed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Fix wings.json (Ubuntu)

  - script: |
      brew install gnu-sed
      DIR=$(basename $CURRENT_DIR)
      gsed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Fix wings.json (MacOS)

  - script: ./pleasew go_mod
    displayName: Regenerate third_party/go/BUILD file
  - script: ./pleasew cover --show_all_output //src/turbine/...
    displayName: Test turbine (with coverage)

- job: cockpit
  pool:
    vmImage: $(imageName)
  strategy:
    matrix:
      ubuntu-node-16-go-1-16-6:
        imageName: "ubuntu-latest"
        nodeVersion: "16.x"
        goVersion: "1.16.6"
      mac-node-16-go-1-16-6:
        imageName: "macos-latest"
        nodeVersion: "16.x"
        goVersion: "1.16.6"

  steps:
  - task: NodeTool@0
    inputs:
      versionSpec: $(nodeVersion)

  - task: Cache@2
    inputs:
      key: "pnpm_store | $(Agent.OS) | package.json"
      path: "/home/vsts/.pnpm-store"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Cache pnpm-store (Ubuntu)

  - task: Cache@2
    inputs:
      key: "pnpm_store | $(Agent.OS) | package.json"
      path: "/Users/runner/.pnpm-store"
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Cache pnpm-store (MacOS)

  - task: Cache@2
    inputs:
      key: "cypress | $(Agent.OS) | package.json"
      path: "/home/vsts/.cache/Cypress"
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Cache Cypress (Ubuntu)

  - task: Cache@2
    inputs:
      key: "cypress | $(Agent.OS) | package.json"
      path: "/Users/runner/Library/Caches/Cypress"
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Cache Cypress (MacOS)

  - script: ./scripts/setup.sh -n
    displayName: Run install script

  - script: |
      DIR=$(basename $CURRENT_DIR)
      sed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Linux')
    displayName: Fix wings.json (Ubuntu)

  - script: |
      brew install gnu-sed
      DIR=$(basename $CURRENT_DIR)
      gsed -i "s/\"GlobeTrotte\"/\"$DIR\"/g" wings.json
      cat wings.json
    env:
      CURRENT_DIR: $(Pipeline.Workspace)
    condition: eq(variables['Agent.OS'], 'Darwin')
    displayName: Fix wings.json (MacOS)

  - script: ./pleasew test --show_all_output //src/cockpit/...
    displayName: Test cockpit
  - script: ./pleasew test --show_all_output //:tsc
    displayName: Cockpit typecheck
