codecov:
  require_ci_to_pass: yes
  branch: main

coverage:
  status:
    project:
      default:
        target: 45%
        threshold: 10%
    patch:
      default:
        target: 45%
        threshold: 10%
  precision: 2
  round: up
  range: "45...100"
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/ec4a1221b10043f1b7e9"

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "**/scripts/**"
  - "src/turbine/logger/*"
  - "jest.config.ts"
  - "vite.config.ts"

  github_checks:
    annotations: true
