codecov:
  require_ci_to_pass: yes
  branch: dev

coverage:
  precision: 2
  round: up
  range: "50...100"
  notify:
    gitter:
      default:
        url: "https://webhooks.gitter.im/e/ec4a1221b10043f1b7e9"
        threshold: 1%

parsers:
  gcov:
    branch_detection:
      conditional: yes
      loop: yes
      method: no
      macro: no

comment:
  layout: "reach,diff,flags,files,footer"
  behavior: default
  require_changes: no

ignore:
  - "**/scripts/**"

github_checks:
    annotations: true
