filegroup(
  name = "core_files",
  srcs = [
    "App.vue",
    "main.ts",
    "shims-vue.d.ts",
    "//src/cockpit/scripts:gen_router",
  ],
  exported_deps = [
    "//src/cockpit/components",
    "//src/cockpit/shared",
    "//src/cockpit/views",
    "//src/cockpit/wings",
  ],
  visibility = ["//..."],
)
