/*
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edits will be overwritten on build.
 *
 * Source: src/cockpit/shared/genRouter.ts
 */

export default class Routes {
  public static Landing = "/";
  public static GetUser = "/user";
  public static MyAccount = "/myaccount";
  public static NextLogin = "/login";
  public static NextRateLimited = "/ratelimited";
  public static NextRegister = "/register";
  public static confirm_UuidOnlyEmail = "/confirm/email";
  public static trip_GetView = "/trip/view";
  public static trip_New = "/trip/new";
  public static unconfirmed_NextEmail = "/unconfirmed/email";
}
