/*
 * DO NOT EDIT THIS FILE DIRCTLY!
 * Edits will be overwritten on build.
 *
 * Source: src/cockpit/shared/genRuter.ts
 */

export default class Rutes {
  public static Landing = "/";
  public static NotFound = "/404";
  public static confirm_Email = "/confirm/email";
  public static password_Reset = "/password/reset";
  public static trip_View = "/trip/view";
  public static trip_New = "/trip/new";
  public static unconfirmed_Email = "/unconfirmed/email";
  public static User = "/user";
  public static Login = "/login";
  public static MyAccount = "/myaccount";
  public static RateLimited = "/ratelimited";
  public static Refresh = "/refresh";
  public static Register = "/register";
}
