/*
 * DO NOT EDIT THIS FILE DIRECTLY!
 * Edits will be overwritten on build.
 *
 * Source: src/cockpit/shared/genRouter.ts
 */

enum Routes {
  Landing = "/",
  NotFound = "/404",
  confirm_Email = "/confirm/email",
  leaving_Confirm = "/leaving/confirm",
  password_Reset = "/password/reset",
  saved_Trips = "/saved/trips",
  trip_View = "/trip/view",
  trip_New = "/trip/new",
  trip_Search = "/trip/search",
  unconfirmed_Email = "/unconfirmed/email",
  User = "/user",
  Login = "/login",
  Logout = "/logout",
  MyAccount = "/myaccount",
  RateLimited = "/ratelimited",
  Refresh = "/refresh",
  Register = "/register",
}
export default Routes;
