go_library(
  name = "email",
  srcs = [
    "email.go",
  ],
  deps = [
    "//third_party:email",
    "//src/turbine/database:database",
    "//src/turbine/wings:wings",
    "//src/turbine/logger:logger",
  ],
  visibility = ["//src/turbine/..."],
)
