go_library(
  name = "wings",
  srcs = [
    "//src/wings/enum:city_#go",
    "//src/wings/enum:access_level_#go",
    "//src/wings/struct:day_#go",
    "//src/wings/struct:trip_#go",
    "//src/wings/struct:user_#go",
    "//src/wings/struct:place_#go",
    "//src/wings/struct:new_user_#go",
    "//src/wings/struct:user_access_level_#go",
  ],
  visibility = ["//src/turbine/..."],
)
