go_library(
  name = "wings",
  srcs = [
    "//src/wings/enum:city",
    "//src/wings/enum:access_level",
    "//src/wings/struct:day",
    "//src/wings/struct:travel_time",
    "//src/wings/struct:trip",
    "//src/wings/struct:user",
    "//src/wings/struct:place",
    "//src/wings/struct:new_user",
    "//src/wings/struct:user_access_level",
    "//src/wings/struct:trip_basic",
    "//src/wings/struct:user_basic",
  ],
  visibility = ["//src/turbine/..."],
)
