// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/enum/city.wings)
// and run the following command:
// plz build //src/wings/...

package wings

type City int

const (
	UNKNOWN          = iota
	SanFranciscoCAUS = iota
	SanJoseCAUS      = iota
	SantaCruzCAUS    = iota
	NewYorkNYUS      = iota
	AnchorageAKUS    = iota
	ParisFR          = iota
	KualaLumpurMY    = iota
	GeorgeTownPGMY   = iota
	SeattleWAUS      = iota
	WashingtonDCUS   = iota
	BostonMAUS       = iota
	PhoneixAZUS      = iota
	PageAZUS         = iota
	LosAngelesCAUS   = iota
	LasVegasNVUS     = iota
)
