// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/day.wings)
// and run the following command:
// plz build //src/wings/...

package wings

// Day - A day of a trip.
type Day struct {
	ID         int          `json:"id"`
	TripID     int          `json:"trip_id"`
	DayOf      int          `json:"day_of"`
	Places     []Place      `json:"places"`
	TravelTime []TravelTime `json:"travel_time"`
}

// GetID (istruct) - Returns the day ID.
func (day Day) GetID() int {
	return day.ID
}

// SetID (istruct) - Sets the day ID.
func (day *Day) SetID(id int) {
	day.ID = id
}

// Days - An array of Day
type Days []Day
