// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/parsed_city.wings)
// and run the following command:
// plz build //src/wings/...

package wings

// ParsedCity - City object queried from DB
type ParsedCity struct {
	ID      int    `json:"id"`
	Display string `json:"display"`
	Iso2    string `json:"iso2"`
}

// ParsedCitys - An array of ParsedCity
type ParsedCitys []ParsedCity
