// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/enum/registration_error.wings)
// and run the following command:
// plz build //src/wings/...

package wings

type RegistrationError int

const (
	InvalidType        = iota
	EmailAlreadyExists = iota
	EmailInvalid       = iota
	UsernameInvalid    = iota
	UsernameTaken      = iota
	UsernameTooShort   = iota
	Success            = iota
)
