// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/travel_time.wings)
// and run the following command:
// plz build //src/wings/...

package wings

// TravelTime - Time take to travel from one place to another.
type TravelTime struct {
	ID            int `json:"id"`
	FromPlaceID   int `json:"from_place_id"`
	ToPlaceID     int `json:"to_place_id"`
	ToPlaceIndex  int `json:"to_place_index"`
	TimeInMinutes int `json:"time_in_minutes"`
}

// TravelTimes - An array of TravelTime
type TravelTimes []TravelTime
