// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/user_basic.wings)
// and run the following command:
// plz build //src/wings/...

package wings

// UserBasic - Basic info of a user.
type UserBasic struct {
	ID        int    `json:"id"`
	Username  string `json:"username"`
	Name      string `json:"name"`
	Bio       string `json:"bio"`
	Link      string `json:"link"`
	Confirmed bool   `json:"confirmed"`
}

// GetID (istruct) - Returns the trip ID.
func (user UserBasic) GetID() int {
	return user.ID
}

// SetID (istruct) - Sets the trip ID.
func (user *UserBasic) SetID(id int) {
	user.ID = id
}

// UserBasics - An array of UserBasic
type UserBasics []UserBasic
