go_library(
  name = "agent",
  srcs = [
    "agent.go",
  ],
  deps = [
    "//src/turbine/logger:logger",
    "//src/turbine/trip:trip",
    "//src/turbine/wings:wings",
  ],
  visibility = ["//src/..."],
)
