filegroup(
  name = "day_test",
  srcs = ["Day.spec.ts"],
  needs_transitive_deps = True,
  visibility = [
    "//:cockpit_unit",
  ],
  deps = ["//src/cockpit/structs:day"],
)

filegroup(
  name = "new_user_test",
  srcs = [
    "NewUser.spec.ts",
  ],
  test_only = True,
  needs_transitive_deps = True,
  visibility = [
    "//:cockpit_unit",
  ],
  deps = ["//src/cockpit/structs:new_user"],
)

filegroup(
  name = "place_test",
  srcs = [
    "Place.spec.ts",
  ],
  test_only = True,
  needs_transitive_deps = True,
  visibility = [
    "//:cockpit_unit",
  ],
  deps = ["//src/cockpit/structs:place"],
)

filegroup(
  name = "trip_test",
  srcs = [
    "Trip.spec.ts",
  ],
  test_only = True,
  needs_transitive_deps = True,
  visibility = [
    "//:cockpit_unit",
  ],
  deps = ["//src/cockpit/structs:trip"],
)

filegroup(
  name = "user_test",
  srcs = [
    "User.spec.ts",
  ],
  test_only = True,
  needs_transitive_deps = True,
  visibility = [
    "//:cockpit_unit",
  ],
  deps = ["//src/cockpit/structs:user"],
)
