// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/registration_response.wings)
// and run the following command:
// plz build //src/wings/...

package user

import (
	wings "github.com/binhonglee/GlobeTrotte/src/turbine/wings"
)

// RegistrationResponse - Response for registration attempt
type RegistrationResponse struct {
	Error wings.RegistrationError `json:"error"`
	User  UserObj                 `json:"user"`
}

// RegistrationResponses - An array of RegistrationResponse
type RegistrationResponses []RegistrationResponse
