go_library(
  name = "trip",
  srcs = [
    "trip.go",
    "//src/wings/struct:trip_obj",
  ],
  deps = [
    "//src/turbine/database",
    "//src/turbine/wings",
  ],
  visibility = ["//src/turbine/..."],
)
