version: 2.1

jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - run: echo "Do nothing lol"

workflows:
  build:
    jobs:
      - build:
          filters:
            branches:
              ignore:
                - deploy
