version: 2.1

orbs:
  cypress: cypress-io/cypress@1.27.0

jobs:
  build:
    docker:
      - image: circleci/golang:1.15.8-node
      - image: circleci/postgres:latest-postgis
        environment:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test

    working_directory: ~/GlobeTrotte

    steps:
      - run: go version
      - run: node --version
      - checkout
      - restore_cache:
          key: please-{{ checksum "pleasew" }}
      - restore_cache:
          key: pnpm-store-{{ checksum "package.json" }}
      - restore_cache:
          key: cypress-6.5.0
      - restore_cache:
          key: node-modules-{{ checksum "package.json" }}
      - run: sudo apt-get install -y libasound2 libgbm-dev libgconf-2-4 libgtk2.0-0 libgtk-3-0 libnotify-dev libnss3 libxcomposite-dev libxcomposite1 libxss1 libxtst6 postgresql-client xauth xvfb
      - run: /usr/bin/Xvfb :99 -screen 0 1920x1080x24+32 &

      - run: echo 'export DISPLAY=:99' >> $BASH_ENV
      - run: echo 'export PATH=/home/circleci/.nimble/bin:$HOME/wings:$PATH' >> $BASH_ENV
      - run: echo 'export USER="circleci"' >> $BASH_ENV
      - run: ./scripts/setup.sh -g -s -w

      - run: sudo npm i -g pnpm
      - run: pnpx cypress install
      - run: cp config/test.psql.config config/psql.config
      - run: cp config/test.email.config config/email.config
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m

      # run tests
      - run: ./pleasew build --show_all_output
      - run: ./pleasew cover --show_all_output //src/turbine/...
      - run: ./pleasew test --show_all_output //src/cockpit/tests/components/...
      - run: ./pleasew test --show_all_output //src/cockpit/tests/views/...
      - run:
          command: ./pleasew work
          background: true
      - run: sleep 1
      - run: ./pleasew test --show_all_output
      - run: ./pleasew report
      - run: ./scripts/leftover.sh
      - save_cache:
          key: please-{{ checksum "pleasew" }}
          paths:
            - ~/.please
      - save_cache:
          key: pnpm-store-{{ checksum "package.json" }}
          paths:
            - ~/.pnpm-store
      - save_cache:
          key: cypress-6.5.0
          paths:
            - ~/.cache/Cypress
      - save_cache:
          key: node-modules-{{ checksum "package.json" }}
          paths:
            - node_modules
      - store_artifacts:
          path: ~/GlobeTrotte/cypress
      - store_artifacts:
          path: ~/GlobeTrotte/coverage
      - store_artifacts:
          path: ~/GlobeTrotte/logs
