plugin_repo(
  name = "shell",
  revision = "v0.2.0",
  plugin = "shell-rules",
  owner = "please-build",
)

plugin_repo(
  name = "go",
  revision = "v1.23.0",
  plugin = "go-rules",
  owner = "please-build",
)
