filegroup(
  name = "trip_editable_test",
  srcs = [
    "TripEditable.spec.ts",
  ],
  needs_transitive_deps = True,
  visibility = [
    "//:cockpit_unit",
  ],
  deps = ["//src/cockpit/shared:trip_editable"],
)

filegroup(
  name = "city_util_test",
  srcs = [
    "CityUtil.spec.ts",
  ],
  needs_transitive_deps = True,
  visibility = [
    "//:cockpit_unit",
  ],
  deps = ["//src/cockpit/shared:city_util"],
)
