filegroup(
  name = "mockData",
  srcs = glob(["**/*.ts"]),
  visibility = ["//src/cockpit/tests/components/..."],
  deps = [
    "//src/cockpit/wings:wings",
    "//src/cockpit/shared:shared",
  ],
)
