filegroup(
  name = "data",
  srcs = ["data.ts"],
  visibility = ["//src/cockpit/tests/components/..."],
  deps = [
    "//src/cockpit/enums:city",
    "//src/cockpit/structs:day",
    "//src/cockpit/structs:trip",
    "//src/cockpit/structs:user",
    "//src/cockpit/structs:place",
    "//src/cockpit/shared:trip_editable",
  ],
)
