package(default_visibility = ["PUBLIC"])

export_file(
  name = "psql.config",
  src = "psql.config",
  test_only = True,
)

export_file(
  name = "email.config",
  src = "email.config",
  test_only = True,
)
