// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/parsed_url_data.wings)
// and run the following command:
// plz build //src/wings/...

package parsing

// ParsedURLData - Parsed data from given URL.
type ParsedURLData struct {
	URL         string         `json:"url"`
	Title       string         `json:"title"`
	Description string         `json:"description"`
	SiteName    string         `json:"site_name"`
	Error       ParsedURLError `json:"error"`
}

// ParsedURLDatas - An array of ParsedURLData
type ParsedURLDatas []ParsedURLData
