filegroup(
  name = "city",
  srcs = [
    "City.ts",
  ],
  visibility = [
    '//src/cockpit:cockpit',
    "//src/cockpit/structs:trip",
    "//src/cockpit/shared:city_util",
    ":city_test",
  ],
)
