go_library(
    name = 'structs',
    srcs = [
        'istructs.go',
        'newuser.go',
        'user.go',
        'trip.go',
    ],
    deps = [
        '//src/turbine/city:city',
        '//src/turbine/place:place',
    ],
    visibility = ['//src/turbine/...'],
)
