go_library(
  name = "structs",
  srcs = [
    "istructs.go",
    "//src/wings/struct:day_#go",
    "//src/wings/struct:new_user_#go",
    "//src/wings/struct:place_#go",
    "//src/wings/struct:trip_#go",
    "//src/wings/struct:user_#go",
  ],
  deps = [
    "//src/turbine/city:city",
  ],
  visibility = ["//src/turbine/..."],
)
