go_binary(
    name = 'main',
    srcs = ['main.go'],
    deps = [
        '//third_party:mux',
        '//third_party:pq',
        '//src/turbine/router',
    ],
    visibility = [
        '//src/turbine/...',
    ],
)
