// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/login_credential.wings)
// and run the following command:
// plz build //src/wings/...

package access

// LoginCredential - Login credential
type LoginCredential struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

// LoginCredentials - An array of LoginCredential
type LoginCredentials []LoginCredential
