// DO NOT EDIT THIS FILE DIRECTLY!
// Edits will be overwritten on build.
//
// If you would like to make any changes, please edit the source file (src/wings/struct/reset_password.wings)
// and run the following command:
// plz build //src/wings/...

package access

// ResetPassword -
type ResetPassword struct {
	Email    string `json:"email"`
	Code     string `json:"code"`
	Password string `json:"password"`
}

// ResetPasswords - An array of ResetPassword
type ResetPasswords []ResetPassword
