filegroup(
  name = "components",
  srcs = [
    "CEditItem.spec.ts",
    "CEditPlaces.spec.ts",
    "CEditTrip.spec.ts",
    "CPlaces.spec.ts",
    "CTripInfo.spec.ts",
    "CViewTrip.spec.ts",
  ],
  visibility = ["//:cockpit_unit"],
)
