filegroup(
  name = "cypress_eslint",
  srcs = [".eslintrc.js"],
  visibility = ["//:cockpit_cypress"],
)

filegroup(
  name = "ava_setup",
  srcs = ["_setup.js"],
  visibility = ["//:cockpit_ava"],
)
