name: Update Go Module

on: [push, pull_request]

jobs:
  no_go_mod:
    if: ${{ !(startsWith(github.event.head_commit.message, 'Update module ') || (startsWith(github.event.head_commit.message, 'Update ') && contains(github.event.head_commit.message, ' digest to '))) }}
    runs-on: ubuntu-latest
    steps:
    - name: Do nothing and print lol
      run: echo "lol"
  update_go_mod:
    if: ${{ startsWith(github.event.head_commit.message, 'Update module ') || (startsWith(github.event.head_commit.message, 'Update ') && contains(github.event.head_commit.message, ' digest to ')) }}
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache please
      id: cache-please
      uses: actions/cache@v1
      with:
        path: ~/.please
        key: ${{ runner.os }}-please
    - name: Use Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Use Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - run: ./pleasew go_mod

    - name: Push commit
      uses: EndBug/add-and-commit@v7
      with:
        message: 'Push changes into BUILD file'
