name: CI
on: [push]
env:
  DISPLAY: :99

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: test
          POSTGRES_DB: test
          POSTGRES_PASSWORD: test
        ports:
          - 5432:5432
    steps:
    - uses: actions/checkout@v2
    - run: /usr/bin/Xvfb :99 -screen 0 1920x1080x24+32 &
    - name: Cache please
      id: cache-please
      uses: actions/cache@v1
      with:
        path: ~/.please
        key: ${{ runner.os }}-please
    - name: Cache pnpm-store
      id: cache-pnpm-store
      uses: actions/cache@v1
      with:
        path: ~/.pnpm-store
        key: ${{ runner.os }}-pnpm-store
    - name: Cache node_modules
      id: cache-node-modules
      uses: actions/cache@v1
      with:
        path: node_modules
        key: ${{ runner.os }}-pnpm
    - name: Cache cypress
      id: cache-cypress
      uses: actions/cache@v1
      with:
        path: ~/.cache/Cypress
        key: ${{ runner.os }}-cypress
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '14'
    - name: Use Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x

    - run: ./scripts/setup.sh -g -s -w
    - run: sudo npm i -g pnpm
    - run: cp .circleci/test.config config/psql.config

    - run: ./pleasew build --show_all_output

    - run: ./pleasew cover --show_all_output //src/turbine/...
    - run: ./pleasew work &
    - run: pnpm i
    - run: pnpm run test:ava
    - run: ./pleasew test --show_all_output

    - run: ./pleasew run //:report
    - run: bash <(curl -s https://codecov.io/bash)
    - run: ./scripts/leftover.sh

